name: "JFrog Worker OIDC Integration"
on: workflow_dispatch
# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write
jobs:
  build:
     runs-on: ubuntu-latest
     env:
      OIDC_AUDIENCE: 'davidro-github'
      OIDC_PROVIDER: 'davidro-github-integration'
     steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v3
         env:  
           JF_URL: ${{ secrets.JF_URL }}
         with:
           oidc-provider-name: ${{ env.OIDC_PROVIDER }}
           oidc-audience: ${{ env.OIDC_AUDIENCE }}
       - name: Connectivity check
         run: |
           jf rt ping
           JFROG_ACCESS_TOKEN=$(jf atc --reference=true --expiry=600 --description="Token for Worker demo. Owner davidro" --grant-admin=true workerci-davidro | jq .reference_token | tr -d '"')
           echo "JFROG_ACCESS_TOKEN=${JFROG_ACCESS_TOKEN}" >> $GITHUB_ENV
       - name: Call Custom Worker endpoint
         uses: fjogeleit/http-request-action@v1
         id: workerExecutionRequest
         with:
            url: "${{ secrets['JF_URL'] }}/worker/api/v1/execute/droActiveUsers"
            method: 'POST'
            escapeData: 'true'
            bearerToken: "${{env.JFROG_ACCESS_TOKEN}}"
            customHeaders: '{"Content-Type": "application/json"}'
            data: |
              {
                "foo": "bar"
              }
       - name: Show Execution response
         run: |
           echo ${{ steps.workerExecutionRequest.outputs.response }}